name: Deploy Environment To Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Environment To Vercel
        run: vercel secrets add DATABASE_URL ${{ secrets.PRODUCTION_DATABASE_URL }} --t ${{ secrets.VERCEL_TOKEN }}
            / vercel secrets add JWT_SECRET ${{ secrets.JWT_SECRET }} --t ${{ secrets.VERCEL_TOKEN }}
            / vercel secrets add NEXT_PUBLIC_FIREBASE_API_KEY ${{ secrets.FIREBASE_API_KEY }} --t ${{ secrets.VERCEL_TOKEN }}
            / vercel secrets add NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ${{ secrets.FIREBASE_AUTH_DOMAIN }} --t ${{ secrets.VERCEL_TOKEN }}
            / vercel secrets add NEXT_PUBLIC_FIREBASE_PROJECT_ID ${{ secrets.FIREBASE_PROJECT_ID }} --t ${{ secrets.VERCEL_TOKEN }}
            / vercel secrets add NEXT_PUBLIC_FIREBASE_APP_ID ${{ secrets.FIREBASE_APP_ID }} --t ${{ secrets.VERCEL_TOKEN }}