name: Deploy Environment To Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Environment To Vercel
        run: vercel env add DATABASE_URL ${{ secrets.PRODUCTION_DATABASE_URL }} --token ${{ secrets.VERCEL_TOKEN }}
            / vercel env add JWT_SECRET ${{ secrets.JWT_SECRET }} --token ${{ secrets.VERCEL_TOKEN }}
            / vercel env add NEXT_PUBLIC_FIREBASE_API_KEY ${{ secrets.FIREBASE_API_KEY }} --token ${{ secrets.VERCEL_TOKEN }}
            / vercel env add NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ${{ secrets.FIREBASE_AUTH_DOMAIN }} --token ${{ secrets.VERCEL_TOKEN }}
            / vercel env add NEXT_PUBLIC_FIREBASE_PROJECT_ID ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.VERCEL_TOKEN }}
            / vercel env add NEXT_PUBLIC_FIREBASE_APP_ID ${{ secrets.FIREBASE_APP_ID }} --token ${{ secrets.VERCEL_TOKEN }}