name: Deploy Environment To Vercel
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Environment To Vercel
        run: vercel secrets add DATABASE_URL ${{ secrets.PRODUCTION_DATABASE_URL }}  --token=${{ secrets.VERCEL_TOKEN }}
            / vercel secrets add JWT_SECRET ${{ secrets.JWT_SECRET }}  --token=${{ secrets.VERCEL_TOKEN }}
            / vercel secrets add NEXT_PUBLIC_FIREBASE_API_KEY ${{ secrets.FIREBASE_API_KEY }}  --token=${{ secrets.VERCEL_TOKEN }}
            / vercel secrets add NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ${{ secrets.FIREBASE_AUTH_DOMAIN }}  --token=${{ secrets.VERCEL_TOKEN }}
            / vercel secrets add NEXT_PUBLIC_FIREBASE_PROJECT_ID ${{ secrets.FIREBASE_PROJECT_ID }}  --token=${{ secrets.VERCEL_TOKEN }}
            / vercel secrets add NEXT_PUBLIC_FIREBASE_APP_ID ${{ secrets.FIREBASE_APP_ID }}  --token=${{ secrets.VERCEL_TOKEN }}