name: Prisma Migrate

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Setup Environment
        run: SET DATABASE_URL=${{ secrets.DEPLOY_DATABASE_URL }}
      - name: Migration
        run: yarn prisma migrate deploy


